version: '2'

services:

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  cassandra:
    image: "datastax/dse-server:6.8.0"
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      - DS_LICENSE=accept
      - BROADCAST_ADDRESS=127.0.0.1
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
